### ISSUE TITLE
Cannot upload assets

### ISSUE THREAD

**Issue by renedacosta** [semantic-release/gitlab#147]
Hi all,

I'm having an issue with uploading assets along with my release.
It seems to find the files fine but is unable to finalize the publish step, giving no errors or indication why it is failing.
The gitlab-CI pipeline indicates that it has run fine but no release is created.
The last debug log that can be seen from the gitlab-runner is: 
```bash
 2020-04-10T21:22:30.883Z semantic-release:gitlab file path: 'CHANGELOG.md'
 2020-04-10T21:22:30.884Z semantic-release:gitlab file label: 'official release files'
```

Here is my plugin config:
```yaml
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogTitle: "# CHANGELOG"
  - "@semantic-release/git"
  - - "@semantic-release/gitlab"
    - assets: [{"path": "*.md", "label": "official release files"}]
```

When the assets object is removed from the config the plugin works fine.

Any clues and ideas are much appreciated!

Thank you
