### ISSUE TITLE
Support `CI_JOB_TOKEN` auth

### ISSUE THREAD

**Issue by dosuken123** [semantic-release/gitlab#156]
GitLab CI injects `CI_JOB_TOKEN` to allow a pipeline job to access a project resource through public v4 API. Not all of APIs support job token auth, however, [release creation API](https://docs.gitlab.com/ee/api/releases/#create-a-release) is already supported. So in theory, executing `GITLAB_TOKEN=$CI_JOB_TOKEN` should be suffice to run semantic-release.

However, as I tested https://gitlab.com/dosuken123/semantic-release-test/-/jobs/628942282, it didn't succeed as semantic-release tried [remote Git repository authentication](https://github.com/semantic-release/gitlab#gitlab-authentication). I'm not sure why it's necessary as the tag creation is done via the above API call.

If `CI_JOB_TOKEN` auth is possible, it's very convenient to run semantic-release in GitLab CI as users don't need to create [PAT](https://github.com/semantic-release/gitlab#gitlab-authentication).

**Comment by mmuenker** [comment]
For me, the `CI_JOB_TOKEN` works fine.

**GitLab**: 13.4.0-pre
**GitLab Runner**: 13.3.1 (shared runner)

**.gitlab-ci.yml**
```yaml
stages:
- release

release:
  needs: []
  image: registry.gitlab.com/rxap/gitlab-ci/semantic-release
  stage: release
  script: semantic-release
  variables:
    GITLAB_TOKEN: $CI_JOB_TOKEN
  interruptible: true
  rules:
  - if: '$CI_COMMIT_REF_NAME == "master"'
    when: on_success
```
