### ISSUE TITLE
[Question] Can this plugin be used for Java Project ? 

### ISSUE THREAD

**Issue by gth7754125** [semantic-release/gitlab#213]
I want to write a `gitlab-ci.yml` with Semantic-Release.
Can it use to java or other language project ?

**Comment by nfriend** [comment]
@gth7754125 I don't see why not!

`semantic-release` runs in Node, but it's pretty agnostic about the actual code being versioned/released.

You'll just have to make sure the job that runs `semantic-release` uses a Node image, for example:

```yml
publish:
  image: node:latest
  script:
    - npm run semantic-release
```
