### ISSUE TITLE
version number in package.json is not updated

### ISSUE THREAD

**Issue by rattkin** [semantic-release/gitlab#215]
I have set up semantic-version in gitlab CI and I get git tags and gitlab releases for every commit in master branch.

I have this in package.json
```
 "release": {
        "plugins": [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            [
                "@semantic-release/gitlab",
                {
                    "gitlabUrl": "https://gitlab.example.com"
                }
            ]
        ]
    },
```

and this in .gitlab-ci.yml
```
semantic-release:
    stage: release
    image: $CI_REGISTRY/dn/docker/node:lts
    before_script:
        - npm install -g semantic-release @semantic-release/gitlab
    script:
        - semantic-release -b $CI_COMMIT_REF_NAME
    tags:
        - docker
    except:
        - tags
    only:
        - master
```
What do I need to add to get the version number changed in package.json?
