### ISSUE TITLE
Failed at step "publish"  with semantic-release/gitlab 6.2.1

### ISSUE THREAD

**Issue by nghnam** [semantic-release/gitlab#250]
Hello everyone. 

I am using `@semantic-release/gitlab` for our project. Here is output of runner
```
[8:30:17 AM] [semantic-release] › ℹ  Running semantic-release version 17.4.4
[8:30:17 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[8:30:17 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:30:17 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:30:17 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[8:30:23 AM] [semantic-release] › ✔  Run automated release from branch master on repository https://gitlab-ci-token:[secure]@gitlab.example.com/example.git
[8:30:23 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:30:23 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:30:23 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.example.com/api/v4)
[8:30:24 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[8:30:24 AM] [semantic-release] › ℹ  Found git tag 1.23.0 associated with version 1.23.0 on branch master
[8:30:24 AM] [semantic-release] › ℹ  Found 4 commits since last release
[8:30:24 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat(apps/products): add testcase
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat(app/bookings): add testcase
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(apps/checkouts):fix_validate invoice and update invetory
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(apps/checkouts): standardize invoice.
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[8:30:24 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 4 commits complete: minor release
[8:30:24 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:30:24 AM] [semantic-release] › ℹ  The next release version is 1.24.0
[8:30:24 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:30:24 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:30:26 AM] [semantic-release] › ✔  Created tag 1.24.0
[8:30:26 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
[8:30:26 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
[8:30:26 AM] [semantic-release] › ✖  An error occurred while running semantic-release: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/node_modules/got/dist/source/as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  pluginName: '@semantic-release/gitlab'
}
HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/node_modules/got/dist/source/as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  pluginName: '@semantic-release/gitlab'
}
```

My config: 
```yaml
branches: ['master']
ci: true
debug: false
dryRun: false
tagFormat: '${version}'

# Global plugin options (will be passed to all plugins)
preset: 'angular' # angular commit message style
gitlabUrl: 'https://gitlab.example.com/' # your gitlab url


plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/gitlab'

verifyConditions:
  - '@semantic-release/gitlab'

analyzeCommits:
  - path: '@semantic-release/commit-analyzer'

generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: 'type'
      commitGroupsSort: 'title'
      commitsSort: 'header'
    linkCompare: true
    linkReferences: true

publish:
  - path: '@semantic-release/gitlab'
```

Version semantic-release: `6.2.1`
Version gitlab:  `14.0.2-ee`

Thanks.
