### ISSUE TITLE
HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by bingling0084** [semantic-release/gitlab#299]
```
[semantic-release] [@semantic-release/gitlab] › ✖  An error occurred while making a request to the GitLab release API:
HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/comoponent-lib/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: undefined,
  timings: {
    start: 1636370892010,
    socket: 1636370892010,
    lookup: 1636370892012,
    connect: 1636370892013,
    secureConnect: 1636370892013,
    upload: 1636370892014,
    response: 1636370892023,
    end: 1636370892023,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 2,
      tcp: 1,
      tls: 0,
      request: 1,
      firstByte: 9,
      download: 0,
      total: 13
    }
  }
}
[11:28:12 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
```
Part of my gitlab CI config:
```
image: node:16

stages:
  - release

publish:
  stage: release
  script:
    - npm install
    - GL_TOKEN=${GL_TOKEN} GITLAB_TOKEN=${GITLAB_TOKEN} GITLAB_URL=https://code.xxxx.org npm run semantic-release
  only:
    - master
```
gitlab version: v11.4.0
"@semantic-release/changelog": "^6.0.1",
"@semantic-release/git": "^10.0.1",
"@semantic-release/gitlab": "^7.0.4",
"@semantic-release/npm": "^8.0.3",
"semantic-release": "^18.0.0"

Thanks for your help.
