### ISSUE TITLE
Plugin is not respecting configuration disabling comments

### ISSUE THREAD

**Issue by altosys** [semantic-release/gitlab#448]
I'm trying to disable the success and fail comments for the plugin, but not succeeding.

I've set up the plugin in my `.releaserc.yml` like this:
```
  - path: "@semantic-release/gitlab"
    gitlabUrl: 'https://gitlab.custom.com'
    successComment:
      issue: false
      mergeRequest: false
    failComment:
      issue: false
      mergeRequest: false
    failTitle: false
    labels: false
    assets:
      - path: "CHANGELOG.md"
        label: "Changelog"
```

I've tried with `false` as both string and yaml boolean (ie unquoted), but in both cases the pipeline fails with this error:
```
[2:24:04 PM] [semantic-release] [@semantic-release/gitlab] › ✖  An error occurred while posting comments to related issues and merge requests:
HTTPError: Response code 502 (Bad Gateway)
``` 
Why is it still trying to post comments, and how do I properly disable it?
