### ISSUE TITLE
No Failures But Package Not Released to Gitlab Registry

### ISSUE THREAD

**Issue by DovahBrownies** [semantic-release/gitlab#472]
Hi guys!
I must be missing something because I've been trying to migrate a package from NPMJS to Gitlab's package registry.
I followed [Gitlab's guide ](https://docs.gitlab.com/ee/ci/examples/semantic-release.html)and everything looks like it's working fine, but nothing shows up in the registry...

Any help with this would be GREATLY appreciated!

Thank you in advance!

## CI Log
![Screen Shot 2022-12-27 at 7 25 25 PM](https://user-images.githubusercontent.com/35106956/209752847-8e5369c1-ae46-49bb-82df-fea5cc66bad0.png)

## `.releaserc.json`
```json
{
  "branches": ["master", "main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/gitlab",
    [
      "@semantic-release/git",
      {
        "assets": ["package.json"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}
```

## `.gitlab-ci.yml`
```yml
default:
  image: node:lts
  before_script:
    - yarn install --frozen-lockfile
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - release

release:
  stage: release
  script:
    - yarn semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 ```
 
 ## `package.json`
 ```json
 {
  "name": "@group/project-name",
  "version": "1.5.0",
  "main": "index.js",
  "devDependencies": {
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/gitlab": "^9.5.1",
    "semantic-release": "^19.0.5",
    ...
  },
  "scripts": {
    "semantic-release": "semantic-release",
  },
  "license": "ISC",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@gitlab.com/<GROUP>/<PROJECT-NAME>.git"
  },
  "homepage": "https://gitlab.com/<GROUP>/<PROJECT-NAME>",
  "bugs": {
    "url": "https://gitlab.com/<GROUP>/<PROJECT-NAME>/issues"
  }
}
```
