### ISSUE TITLE
GitLab release is not being created

### ISSUE THREAD

**Issue by amimas** [semantic-release/gitlab#496]
Hello - I'm new to semantic-release. On top of that I'm trying to automate release of a non-npm package. I'm using this plugin with semantic-release and when I run it, I see the git tag being created in the gitlab project, but I don't see a corresponding "GitLab Release".

I'm not sure what I might be missing in terms of configurations. Here's my semantic-release config (`.releaserc.yaml`). I'm running `semantic-release` from the `prerelease` branch.

```yaml
branches:
  - main
  - name: prerelease
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer":
    preset: conventionalcommits,
    releaseRules:
      - type: docs
        release: patch
      - type: refactor
        release: patch
      - type: style
        release: patch
    parserOpts:
      # Commits containing following keywords will be considered breaking changes
      noteKeywords:
        - BREAKING CHANGE
        - BREAKING-CHANGE
        - BREAKING CHANGES
        - BREAKING-CHANGES
  - "@semantic-release/release-notes-generator":
    parserOpts:
      # Commits containing following keywords will be considered breaking changes
      noteKeywords:
        - BREAKING CHANGE
        - BREAKING-CHANGE
        - BREAKING CHANGES
        - BREAKING-CHANGES
  - "@semantic-release/exec":
    execCwd: "scripts"
    publishCmd: "./publish.sh ${nextRelease.version}"
  - "@semantic-release/gitlab":
    gitlabUrl: "https://gitlab.example.com"
```

Appreciate if you could point out any obvious config issue. Here's a snippet of output from `semantic-release` command:

```
[10:27:35 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:27:35 PM] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0-prerelease.1
[10:27:37 PM] [semantic-release] › ✔  Created tag v1.0.0-prerelease.1
[10:27:37 PM] [semantic-release] › ✔  Published release 1.0.0-prerelease.1 on prerelease channel
Done in 7.17s.
```

**Comment by amimas** [comment]
I was wondering if doing release from `main` branch would make a difference. Looks like I have the same issue from that branch also. A git tag is created in the GitLab project, but there aren't any GitLab Release created.

**Comment by JonasSchubert** [comment]
Hi @amimas.
I think your yaml file might be malformed and the plugins will not be loaded proberly.
Can you try following yaml configuration:
```yaml
branches:
- main
- name: prerelease
  prerelease: true
plugins:
- - "@semantic-release/commit-analyzer"
  - preset: conventionalcommits
    releaseRules:
    - type: docs
      release: patch
    - type: refactor
      release: patch
    - type: style
      release: patch
    parserOpts:
    # Commits containing following keywords will be considered breaking changes
    noteKeywords:
    - BREAKING CHANGE
    - BREAKING-CHANGE
    - BREAKING CHANGES
    - BREAKING-CHANGES
- - "@semantic-release/release-notes-generator"
  - parserOpts:
    # Commits containing following keywords will be considered breaking changes
    noteKeywords:
    - BREAKING CHANGE
    - BREAKING-CHANGE
    - BREAKING CHANGES
    - BREAKING-CHANGES
- - "@semantic-release/exec"
  - execCwd: "scripts"
  - publishCmd: "./publish.sh ${nextRelease.version}"
- - "@semantic-release/gitlab"
  - gitlabUrl: "https://gitlab.example.com"
```
