### ISSUE TITLE
feature request: Allow dryrun to execute even in Merge request pipeline (avoid duplicated pipelines)

### ISSUE THREAD

**Issue by tringuyen-yw** [semantic-release/gitlab#566]
Using Gtlab runner version `16.0.0`, the image used to run `semantic-release` is from a docker image we created by:

```
FROM node:20-alpine

RUN apk --update-cache --no-cache upgrade
RUN apk add --update --no-cache git openssh
RUN npm install --global semantic-release @semantic-release/gitlab
```
Gitlab job:

```yaml
sem-release-dryrun:
  image: "our-semantic-release-image:latest"
  stage: semantic-release
  script:
    semantic-release --dry-run --branches $CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_REF_NAME
```

When a commit is pushed within a Merge request, the job rules above will trigger TWO pipelines:

1. A "Merge request" pipeline, where `semantic-release`, and simply terminate, skipping all its dryrun tasks:

```
[semantic-release] › ℹ  This run was triggered by a pull request and therefore a new version won't be published.
```

2. A "Branch" pipeline (on the branch used to create the MR). In this pipeline, somehow  `semantic-release` is OK to executes its dryrun tasks. The job logs showed:

```
  [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 3 commits complete: patch release
  [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
  [semantic-release] › ℹ  The next release version is 2.144.1
  [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
  [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
  [semantic-release] › ⚠  Skip v2.144.1 tag creation in dry-run mode
  [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/gitlab" in dry-run mode
```

**QUESTION:**
- Is it really useful to skip drydun tasks withing a Mergerequest/PullRequest pipeline ?
- In case it is, would it be OK to have a flag , like `--allow-dryrun-in-mr` to override that behavior? 

In our use-case, this would allow us to refine our job rules so we can eliminate the duplicate pipeline. ie. Running `semantic-release --dry-run` in the "merge request" pipeline is plentyful enough.
