### ISSUE TITLE
CHANGELOG.md isn' generated in Gitlab CI

### ISSUE THREAD

**Issue by chekhovana** [semantic-release/gitlab#741]
Hello, I'm trying to add semantic-release to my test gitlab project. Tags are created, but changelog is missing. Here's my configuration:

**.gitlab-ci.yml**
 ```
stages:
  - release

release:
  image: node:latest
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/changelog @semantic-release/commit-analyzer
  script:
    - npx semantic-release --debug
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

```
**package.json**
```
{
  "name": "testsemver",
  "release": {
    "branches": ["main"],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/gitlab",
      "@semantic-release/changelog"
    ]
  }
}
```
In [pipeline job log](https://github.com/user-attachments/files/15830491/pipeline.log) there is the error caused by failed push attempt with ssh auth. Is that the reason? Should I configure ssh auth in addition to created access token? Or something else is wrong?
